# Generated by Django 4.2.15 on 2024-08-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('short_code', models.CharField(default='Iz5c', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('long_url', models.CharField(max_length=30)),
                ('visits_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
