# Generated by Django 4.2.15 on 2024-08-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(blank=True, max_length=255, unique=True)),
                ('long_url', models.CharField(max_length=500)),
                ('visits_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_expired', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
