# Generated by Django 4.2.15 on 2024-08-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='long_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_code',
            field=models.CharField(default='L4ee', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
