# Generated by Django 4.2.15 on 2024-08-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_url_long_url_alter_url_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='url',
            name='short_code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
